user:
  outputs:
    default:
      keyfile_json:
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        auth_uri: https://accounts.google.com/o/oauth2/auth
        client_email: khwezi-zoomcamp@zoomcamp-demo.iam.gserviceaccount.com
        client_id: '111978431725291477451'
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/khwezi-zoomcamp%40zoomcamp-demo.iam.gserviceaccount.com
        private_key: '-----BEGIN PRIVATE KEY-----

          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMja2306c/UGG4

          +FV8mvU7mDxU6DAUh/qgSuUlJ3wKXFqx2L0MBPsCkij0xnnER54YLIJU8dDMOH1o

          Zvbx8fEKyS1v50slaBE9yC7C/8uiPLkj95yTUR652JuciOx8a/9nsPNCxfFJ8E+s

          bK8X4r3xJKDRutrKoS6DOogHH7F6VP4QMMoo8cj/rdLQ2k227t5NZ1RzZr/efUwQ

          whonfnP0JaWBO0hdSLh2jAEFQ2eG2kf/RrvJOPl1SxdpXfn/GDbi4B6YxW/5uPhp

          ep0aBEw9XbN+Q8FgxpxB2UTM24wXJOeMI30KxevG6LQ49ruQhn24MTBBwKWvK5vE

          rsP6p231AgMBAAECggEAHbOEwehtpHfbeKw2XX1yllCokfuU36ZO8e9uDlMJY8e9

          M42xBYnDmL/4SnJ3Q9TSU9hCpGroUn7xVrN8r+zdfx9vBYykEK5nsnzarV3PB6Oh

          jmNpzMo+l+Wn0rbe/8H+t+OtrshnHMFUEElHs0QtKFKVN17WXg3BXzSkg8RKVOS3

          xKZh+iCyIGHsYS+xViHPPUZYo5BhZZyg9WRPRuFxwj1puOEhLIZfcd6A1C9CDFTS

          q8Byi0svDWgxBF07r0w+DfaaCgioZYGZXVKAcvHubptGXuD2Xg/7JSfWFx/aq/mS

          Qqm51kLW8nkTnY1o+/TOm/OPMqiCnpnZI3WRp8vWkQKBgQD31i8JJty3r9S+97V8

          D2l7YRN+Xo+s0nUvI91k+b7k1beMpfHv+MvJCA6fhsm45lrup0VXyNFhr/2AGdEd

          xcUVJjqiWjZQVzVRvyAWptrKW19hoepSL9sE6XIYb3C0P3NtYONydwcWKJXV4QJ8

          Xk+ZMiVkm4lg+E75G2rcBCBcHwKBgQDTSoVJw7SJRB4IrlBVGkEgOw3W5BDxGMhW

          +r2gwUKARwVJpiivS6SJMn/kDuIcE1iHfgPNyZXorRyQaKuG++HkO7bPaI+0Lv83

          NlsD/V/riiOiL6f0b7NHk7j50SbJUe4AIojFYqhrX7HwIsSdo7Fjsjb4I7HoTYA0

          +SU1MGFzawKBgB2umDmHXv3c4CTy89hk3CQ7ryL+XkS7e+9mYziZtKQheHcu1LgB

          2x47iczPTs+HPzK/880crv79HeY+sU3Yhs8Oog0ZstGScD9XHZe46hE8OkMuKisn

          shp3fwOwLRZZVxCtfvARk1azC6bu6OZOQUg+uj2/ZwenFYY+I2EwWVPPAoGAHEL1

          fR5eQZYI5mRafmeamnMLsNiko3sLIQc84gm3mWzmeilte7UEdw14KcsL13GG/+iN

          HbN/B7ZQAcjeWJnMZzjNhQSZZCJ9JKdymSAE+n5pscHqFznxovtRXKjrJTZ+PSph

          XPWLTYFpTZN49RT2Hz2xOJOdslLbeTpyDaFBB60CgYEAqQRfX/kvbfp0bg+9XGpy

          dPmZWmOph8qFT/vR12oviu/tuDv6mNcP9NEh5bwuxgwK2Vqn0VqJmOkLjisI4qIy

          ZIezd82VcCp0bPVDjZAKvDl9/phxza6Bl40c5BPqpIJMPh50X1jWDeTL/VL5S98a

          /OgwWmu4+ZRtKxXHxUxmVE4=

          -----END PRIVATE KEY-----

          '
        private_key_id: 1fd2f7ac540b9e40521a49eb2530c534d4a572a7
        project_id: zoomcamp-demo
        token_uri: https://oauth2.googleapis.com/token
        type: service_account
      method: service-account-json
      project: zoomcamp-demo
      schema: dbt_kkgalema
      scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
      - https://www.googleapis.com/auth/userinfo.email
      target_name: default
      type: bigquery
  target: default
